### ISSUE TITLE
Error with setuptools-34.3.3

### ISSUE THREAD

**Issue by stuartz-VernonCo** [nginxinc/nginx-amplify-doc#18]
Alpine 3.4

setuptools-34.3.3 causes an error with 
File "/nginx-amplify-agent/amplify/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

doesn't happen with setuptools-33.1.1
http://stackoverflow.com/a/42035091/1516104

OR setting File "/nginx-amplify-agent/amplify/packaging/requirements.py", line 59 as
    MARKER_EXPR = originalTextFor(MARKER_EXPR(""))("marker")
allows for successful completion

**Comment by nkashiv** [comment]
@stuartz-VernonCo If you are still facing this problem, please create an issue in the [NGINX Amplify Agent repo](https://github.com/nginxinc/nginx-amplify-agent/issues)
