### ISSUE TITLE
dpkg: error processing package nginx-amplify-agent (--configure):

### ISSUE THREAD

**Issue by scottstensland** [nginxinc/nginx-amplify-doc#2]
Hi

on ubuntu 16.04 getting

```
sudo apt-get install nginx-amplify-agent 
```

Reading package lists... Done
Building dependency tree  
Reading state information... Done
nginx-amplify-agent is already the newest version (0.33-1~xenial).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up nginx-amplify-agent (0.33-1~xenial) ...
dpkg: error processing package nginx-amplify-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 nginx-amplify-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)

This is on a dev laptop so not prod - I can help t/s further  ...   just give a nod

**Comment by ptreyes** [comment]
Can you please do the following?

# dpkg -s nginx-amplify-agent
# ls -la /etc/amplify-agent

**Comment by scottstensland** [comment]
Here you go


     dpkg -s nginx-amplify-agent


Package: nginx-amplify-agent
Status: install ok half-configured
Priority: optional
Section: python
Maintainer: Mike Belov <dedm@nginx.com>
Architecture: amd64
Version: 0.33-3~xenial
Config-Version: 0.32-1~xenial
Depends: python (>= 2.6), lsb-release
Description: NGINX Amplify Agent
  The NGINX Amplify Agent is a small, Python application that provides
  system and NGINX metric collection. It is part of NGINX Amplify -
  the monitoring and configuration assistance service for NGINX.
  .
  This package installs and runs NGINX Amplify Agent daemon.
  .
  See http://nginx.com/amplify for more information
License: 2-clause BSD-like license
Homepage: https://github.com/nginxinc



                     ls -la /etc/amplify-agent

total 24
drwxrwxr-x   2 root     root  4096 May  5 14:45 .
drwxr-xr-x 159 root     root 12288 May  7 14:45 ..
-rw-r--r--   1 www-data root  1212 Apr 26 11:20 agent.conf
-rw-r--r--   1 root     root  1244 May  5 10:15 agent.conf.default
stens@bodhisattva ~ $
stens@bodhisattva ~ $




cheers,
Scott

    A man who fears suffering is already suffering from what he fears.
        - Michel de Montaigne

**Comment by scottstensland** [comment]
I fixed this issue by re-installing

this does not seem right

ls -la /etc/amplify-agent
total 24
drwxrwxr-x   2 root     root  4096 May  5 14:45 .
drwxr-xr-x 159 root     root 12288 May  7 14:45 ..
-rw-r--r--   1 www-data root  1212 Apr 26 11:20 agent.conf
-rw-r--r--   1 root     root  1244 May  5 10:15 agent.conf.default


somehow two conf files got into above dir  ... then all was well after I issued 

sudo apt-get remove --purge nginx-amplify-agent
sudo apt-get install nginx-amplify-agent
