### ISSUE TITLE
Fedora OS Support

### ISSUE THREAD

**Issue by Abhinav1217** [nginxinc/nginx-amplify-doc#3]
I just got my invite to Amplify. But quickly got sad as my server is Fedora Cloud 23 on Digitalocean and Fedora server at home. I had read FAQ and thought that since script is supporting RHEL 7 ( [which is derived from fedora 20](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Relationship_with_Fedora) with features back ported from all the way from F22. ) It should work well in F23. But it looks like there is no repo for  fedora. 

When can I be able to use this with Fedora Server and Fedora Cloud?

**Comment by dedm** [comment]
@Abhinav1217  we released a beta script for installing agent in non-supported systems: https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh

Please try it and tell us how it was.
