### ISSUE TITLE
Stub_status.conf, 'stub_status on' vs 'stub_status'

### ISSUE THREAD

**Issue by dave4you** [nginxinc/nginx-amplify-doc#31]
Hi,

It seems that within stub_status.conf, 'stub_status on'  and 'stub_status' have the same effect.
What I learned online is that it might have something to do with changes made in version 1.7.5.
However I don't see this reflected in the documentation. 

stub_status;    # freely available with open source NGINX ?
stub_status on;     # for open source NGINX < version 1.7.5 ?
status;    # available only with NGINX Plus ?
_source: https://docs.datadoghq.com/integrations/nginx/_

Curious to learn about the effects of the different options.

Kind regards,

Dave

**Comment by jputrino** [comment]
According to the [`ngx_http_stub_status_module` docs](https://nginx.org/en/docs/http/ngx_http_stub_status_module.html), 

> In versions prior to 1.7.5, the directive syntax required an arbitrary argument, for example, “stub_status on”.

---

The [ngx_http_status_module](https://nginx.org/en/docs/http/ngx_http_status_module.html) was available as part of NGINX Plus until 1.13.10. It was superseded by the [ngx_http_api_module](https://nginx.org/en/docs/http/ngx_http_api_module.html) module in 1.13.3. This module also requires a commercial license.
