### ISSUE TITLE
Fail on Ubuntu 16.04

### ISSUE THREAD

**Issue by maitrungduc1410** [nginxinc/nginx-amplify-doc#33]
I'm having the same problem when install Amplify on Ubuntu 16.04.

The issue looks like below:

<img width="913" alt="Screenshot 2019-12-15 at 22 16 47" src="https://user-images.githubusercontent.com/16630193/70864092-cee02c80-1f89-11ea-819c-ae696b77f42e.png">

I follow the instruction by doing the following steps with root permission:
```
curl -L -O https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.shv
API_KEY='<my_api_key>' sh ./install.sh
```

Does anyone know how to solve this?

Thank you

**Comment by defanator** [comment]
The reason was in broken ppa repository (ffmpeg-4).
