### ISSUE TITLE
amplify web interface support email invalid

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [nginxinc/nginx-amplify-doc#35]
on web interface, top right click on username -> support

> For Amplify support, please send email to amplify-support@nginx.com.

This is not a valid email
> amplify-support@nginx.com INVALID_ADDRESS, ERROR_CODE :554, ERROR_CODE :5.7.1 <amplify-support@nginx.com>: Recipient address rejected: envelope-sender address is not listed as permitted for the request tracker. You are either do not bind email to support contract or From: address differ from envelope address

**Comment by defanator** [comment]
@jkldgoefgkljefogeg what is your email address you're trying to use when communicating via amplify-support@nginx.com? (It should be the one you use to log in Amplify web UI, and it _must_ be verified.)

**Comment by jkldgoefgkljefogeg** [comment]
oh I used a different email address. Would be good to add a note on that page asking people to write from the account email.

Btw I no longer have access to the login email I signed up for amplify. I added another email but there is no way to delete the original one.

**Comment by justin27c** [comment]
With relation to this issue, I am trying to send e-mail to support from the same email registered on nginx amplify however still getting response.

Reported error:	554 5.7.1 <amplify-support@nginx.com>: Recipient address rejected: envelope-sender address is not listed as permitted for the request tracker. You are either do not bind email to support contract or From: address differ from envelope address

**Comment by nkashiv** [comment]
The support process for Amplify now uses https://my.f5.com/
Please enable NGINX Amplify Agent’s [debug log](https://docs.nginx.com/nginx-amplify/nginx-amplify-agent/install/configuring-amplify-agent/#agent-logfile), restart NGINX Amplify Agent, wait a few minutes, and then create a support request through https://my.f5.com/, please attach the debug log to the support case.
