### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by pyprism** [nginxinc/nginx-amplify-doc#37]
Please add release support for Ubuntu 20.04 . Currently we can't install amplify agent in Ubuntu 20.04
```
# error.log
Get:11 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]     
Ign:12 https://packages.amplify.nginx.com/ubuntu focal InRelease               
Get:13 https://packages.amplify.nginx.com/ubuntu focal Release [3,278 B]       
Ign:14 https://packages.amplify.nginx.com/ubuntu focal Release.gpg
Reading package lists... Done
E: The repository 'https://packages.amplify.nginx.com/ubuntu focal Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

  8. Updating repository ... failed.

 Please check the list of the supported systems here https://git.io/vKkev

```

**Comment by WarpWing** [comment]
+1

**Comment by rodrigogmartins** [comment]
+1

**Comment by defanator** [comment]
@pyprism @Malacarne @WarpWing @rodrigogmartins could you please check this one? https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703

(We do have nginx-amplify-agent package built for Ubuntu 20.04 but it is currently not advertised in install.sh and docs - appreciate any feedback if you will be able to test this though.)

**Comment by ltsaiete** [comment]
I'm also facing the same issue.

**Comment by ekremyurdakul** [comment]
+1

**Comment by kroko** [comment]
+1

**Comment by foldas** [comment]
+1

**Comment by tungdh1** [comment]
Please support Ubuntu 20.04. This version is released on April 23, 2020. It's been almost a year, but there's still no support yet.

**Comment by fahadahammed** [comment]
Still facing this issue...

**Comment by defanator** [comment]
Gentlemen, sorry for not being responsive enough - there **is** an agent package for Ubuntu 20.04, installation instructions are here: https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703

Appreciate any feedback once you're able to test that one.

**Comment by danijelk** [comment]
> Gentlemen, sorry for not being responsive enough - there **is** an agent package for Ubuntu 20.04, installation instructions are here: [nginxinc/nginx-amplify-agent#181 (comment)](https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703)
> 
> Appreciate any feedback once you're able to test that one.

Any chance for an arm64 package to test?

**Comment by defanator** [comment]
> Any chance for an arm64 package to test?

@danijelk will try to submit arm64 version to the same repo later this week.

**Comment by nathanmillar16** [comment]
thank you @defanator . That would be awesome if you could

**Comment by yukebrillianth** [comment]
when to support ubuntu 20.04?

**Comment by defanator** [comment]
@danijelk @nathanmillar16 arm64 version of the latest nginx-amplify-agent package for Ubuntu 20.04 is now available via the same repository described here - https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703

**Comment by danijelk** [comment]
> @danijelk @nathanmillar16 arm64 version of the latest nginx-amplify-agent package for Ubuntu 20.04 is now available via the same repository described here - [nginxinc/nginx-amplify-agent#181 (comment)](https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703)

Thanks works great
```

 Launching amplify-agent ...
 All done.
```

Will write if there are any issues.

**Comment by chrisc0** [comment]
> @danijelk @nathanmillar16 arm64 version of the latest nginx-amplify-agent package for Ubuntu 20.04 is now available via the same repository described here - [nginxinc/nginx-amplify-agent#181 (comment)](https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703)


Was this tested in 20.04.2? I tried running the install in 20.04.1 and it worked fine.  I tried it in 20.04.2 and I get this error:

```
  9. Installing nginx-amplify-agent package ...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx-amplify-agent : Depends: libffi6 (>= 3.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

  9. Installing nginx-amplify-agent package ... failed.
```

Thanks,
Chris

**Comment by defanator** [comment]
@chrisc0 are you observing this with amd64 or aarch64 package?

**Comment by chrisc0** [comment]
The arm64 package

**Comment by danijelk** [comment]
> > @danijelk @nathanmillar16 arm64 version of the latest nginx-amplify-agent package for Ubuntu 20.04 is now available via the same repository described here - [nginxinc/nginx-amplify-agent#181 (comment)](https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703)
> 
> Was this tested in 20.04.2? I tried running the install in 20.04.1 and it worked fine. I tried it in 20.04.2 and I get this error:
> 
> ```
>   9. Installing nginx-amplify-agent package ...
> 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  nginx-amplify-agent : Depends: libffi6 (>= 3.2) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> 
>   9. Installing nginx-amplify-agent package ... failed.
> ```
> 
> Thanks,
> Chris

lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Comment by chrisc0** [comment]
I went through all the steps again and it's working now.  Thanks.  Hopefully we can get a real release soon so we don't have do these temporary workarounds.

**Comment by nathanmillar16** [comment]
@chrisc0 what steps did you follow? I'm  also getting errors :(

**Comment by nathanmillar16** [comment]
Legends. Thank you @defanator

**Comment by igorbarinov** [comment]
> Gentlemen, sorry for not being responsive enough - there **is** an agent package for Ubuntu 20.04, installation instructions are here: [nginxinc/nginx-amplify-agent#181 (comment)](https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703)
> 
> Appreciate any feedback once you're able to test that one.

thanks. how to setup API key after installation of the agent from the deb file?
thank you in advance

**Comment by defanator** [comment]
Latest agent version (1.8.0) now officially supports Ubuntu 20.04 for both amd64 and arm64:

https://amplify.nginx.com/docs/faq-2-nginx-amplify-agent.html#21-what-operating-systems-are-supported

Please follow the docs in order to upgrade from previous versions:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent

**Comment by veris-developer** [comment]
please help with this

**Comment by defanator** [comment]
@veris-developer please follow this doc:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent

Correct apt repository listing for 20.04 "focal" should be:
```
deb https://packages.amplify.nginx.com/py3/ubuntu/ focal amplify-agent
```
