### ISSUE TITLE
Better docs for extended log format

### ISSUE THREAD

**Issue by ingria** [nginxinc/nginx-amplify-doc#38]
Some metrics require the additional variables to be added into the log format, but it is unclear where to put it.

For example, description for `nginx.http.gzip.ratio` says:

> Achieved compression ratio, calculated as the ratio between the original and compressed response sizes.
> Source: access.log (requires custom log format)
> Variable: $gzip_ratio

But the [docs](https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#additional-nginx-metrics) for log format doesn't say anything about this variable and doesn't provide an example.

**Comment by inyerade** [comment]
I m also looking for $gzip_ratio in the log format, and nothing

**Comment by jputrino** [comment]
For others who may be looking for similar information -- the `nginx.http.gzip.ratio` variable `$gzip_ratio` can be used in the access.log log format in the same manner shown in the example in the NGINX Amplify Metrics and Metadata docs: [NGINX Metrics - Additional NGINX Metrics](https://docs.nginx.com/nginx-amplify/metrics-metadata/nginx-metrics/#additional-nginx-metrics). 

The example in the NGINX admin guide that demonstrates how to configure logging includes the `gzip_ratio` variable: [Setting Up the Access Log](https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#setting-up-the-access-log)
