### ISSUE TITLE
Way to list request_uri whit X condition?

### ISSUE THREAD

**Issue by inyerade** [nginxinc/nginx-amplify-doc#40]
I want to know the top 5 (or 3) request_uri with most time response also the top request_uri with status 500 and some like this. Amplify have this?

**Comment by nkashiv** [comment]
@inyerade You can partially achieve this by creating a [custom dashboard](https://docs.nginx.com/nginx-amplify/user-interface/dashboards/) with a graph for each `request_uri` to monitor the 500 status / response time, but we do not rank them.
