### ISSUE TITLE
Python 3 / 20.04LTS

### ISSUE THREAD

**Issue by jshep321** [nginxinc/nginx-amplify-doc#41]
Hi,
Any schedule to support 20.04.xLTS w/ the default python (3.8.5 as of today)?  It's the new default!

Thanks!

**Comment by defanator** [comment]
@jshep321 latest agent version (1.8.0) is now Python 3 based and officially supports Ubuntu 20.04 "focal". Please follow the docs in order to upgrade from previous versions:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent
