### ISSUE TITLE
Cannot fully uninstall

### ISSUE THREAD

**Issue by jfinkel** [nginxinc/nginx-amplify-doc#43]
Amplify did not work for me, so I uninstalled it using:

`apt-get remove nginx-amplify-agent`

But now when I try to update, I get this:

`
$ sudo apt update                                                        
Hit:1 http://mirrors.linode.com/ubuntu hirsute InRelease
Hit:2 http://mirrors.linode.com/ubuntu hirsute-updates InRelease                  
Hit:3 http://mirrors.linode.com/ubuntu hirsute-backports InRelease                
Hit:4 http://mirrors.linode.com/ubuntu hirsute-security InRelease                 
Ign:5 https://packages.amplify.nginx.com/ubuntu/dists focal InRelease             
Err:6 https://packages.amplify.nginx.com/ubuntu/dists focal Release
  404  Not Found [IP: 52.24.43.197 443]
Reading package lists... Done
E: The repository 'https://packages.amplify.nginx.com/ubuntu/dists focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**How do I correct this?  Thank you.**

**Comment by jfinkel** [comment]
Answering my own question, I deleted a residual Amplify file in /etc/apt/sources.list.d/

**Comment by hartho1812** [comment]
thank you for the solution.
