### ISSUE TITLE
Support ARM64 on Debian 10

### ISSUE THREAD

**Issue by one-and-only** [nginxinc/nginx-amplify-doc#44]
I have a raspberry pi 4 running a LEMP stack that I would like Amplify installed on, but ARM64 only seems to be supported on Ubuntu 18.04/16.04. Will ARM64 versions of Amplify be available for Debian 10 in the near future?

**Comment by defanator** [comment]
@one-and-only latest agent version (1.8.0) now supports Debian 10 for ARM:

https://amplify.nginx.com/docs/faq-2-nginx-amplify-agent.html#21-what-operating-systems-are-supported
