### ISSUE TITLE
You are either do not bind email to support contract or From: address differ from envelope address

### ISSUE THREAD

**Issue by licsuj27** [nginxinc/nginx-amplify-doc#45]
I am trying to send e-mail to support from the same email registered on nginx amplify however still getting response.

Reported error: 554 5.7.1 amplify-support@nginx.com: Recipient address rejected: envelope-sender address is not listed as permitted for the request tracker. You are either do not bind email to support contract or From: address differ from envelope address

anyone can confirm what the issue might be?

**Comment by defanator** [comment]
@justin27c could you please contact me via a.belov at f5 dot com?
