### ISSUE TITLE
I am not receiving any "forgot password" reset password emails but get notifications on the portal.

### ISSUE THREAD

**Issue by davidsaliba** [nginxinc/nginx-amplify-doc#46]
Hi,
I was evaluating amplify and I liked it.

I removed a site and am getting notifications but cannot log in. I tried many times issueing a password reset (using the same email address i have in my welcome email) but to no avail.
Can someone put me in touch with someone who can help please?
I will give my email address on a private message but not here..
d.

**Comment by defanator** [comment]
@davidsaliba could you please contact me via a.belov at f5 dot com please?

**Comment by davidcarma** [comment]
Sent you a confirmation email. Thanks
