### ISSUE TITLE
Website https://amplify.nginx.com/ not working after login

### ISSUE THREAD

**Issue by cetm-rj** [nginxinc/nginx-amplify-doc#51]
I don't know if this is the right place for support but for some time now I can't use this service anymore. After logging in, the website https://amplify.nginx.com/overview is just blank. The browser console shows various errors (404) which might explain this behavior.
Attached is a screenshot:
![image](https://user-images.githubusercontent.com/87851673/174739811-603593ee-5d3b-4002-a72d-d810bc444984.png)

**Comment by Giners** [comment]
Given the stale nature of this bug and it being unrelated to Amplify documentation the team has decided to close this bug.

If you believe there is still an issue please open a new bug in the following repo: https://github.com/nginxinc/nginx-amplify-agent
