### ISSUE TITLE
Not Installing Agent at Amazon Linux 2

### ISSUE THREAD

**Issue by danidorado** [nginxinc/nginx-amplify-doc#52]
Hello, I'm getting this errors when installing at my ec2 instance. I have both python 2.7 and 3.8 present on the system

Error: Package: python36-pysocks-1.6.8-7.el7.noarch (epel)
           Requires: python(abi) = 3.6
           Installed: python-2.7.18-1.amzn2.0.5.x86_64 (@amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Installed: python3-3.7.10-1.amzn2.0.1.x86_64 (@amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Installed: python38-3.8.5-1.amzn2.0.2.x86_64 (@amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python-2.7.5-58.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-2.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-4.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-5.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python3-3.7.0-0.12.b2.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.16.b3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.1-9.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.2-4.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.4.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.6-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.8-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python34-3.4.10-8.el7.x86_64 (epel)
               python(abi) = 3.4
           Available: python38-3.8.2-2.amzn2.0.5.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.3-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.5-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
Error: Package: python36-idna-2.10-1.el7.noarch (epel)
           Requires: python(abi) = 3.6
           Installed: python-2.7.18-1.amzn2.0.5.x86_64 (@amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Installed: python3-3.7.10-1.amzn2.0.1.x86_64 (@amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Installed: python38-3.8.5-1.amzn2.0.2.x86_64 (@amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python-2.7.5-58.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-2.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-4.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-5.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python3-3.7.0-0.12.b2.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.16.b3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.1-9.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.2-4.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.4.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.6-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.8-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python34-3.4.10-8.el7.x86_64 (epel)
               python(abi) = 3.4
           Available: python38-3.8.2-2.amzn2.0.5.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.3-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.5-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
Error: Package: python36-chardet-3.0.4-1.el7.noarch (epel)
           Requires: python(abi) = 3.6
           Installed: python-2.7.18-1.amzn2.0.5.x86_64 (@amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Installed: python3-3.7.10-1.amzn2.0.1.x86_64 (@amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Installed: python38-3.8.5-1.amzn2.0.2.x86_64 (@amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python-2.7.5-58.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-2.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-4.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-5.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python3-3.7.0-0.12.b2.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.16.b3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.1-9.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.2-4.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.4.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.6-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.8-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python34-3.4.10-8.el7.x86_64 (epel)
               python(abi) = 3.4
           Available: python38-3.8.2-2.amzn2.0.5.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.3-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.5-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
Error: Package: python36-requests-2.14.2-2.el7.noarch (epel)
           Requires: python(abi) = 3.6
           Installed: python-2.7.18-1.amzn2.0.5.x86_64 (@amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Installed: python3-3.7.10-1.amzn2.0.1.x86_64 (@amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Installed: python38-3.8.5-1.amzn2.0.2.x86_64 (@amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python-2.7.5-58.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-2.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-4.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-5.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python3-3.7.0-0.12.b2.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.16.b3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.1-9.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.2-4.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.4.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.6-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.8-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python34-3.4.10-8.el7.x86_64 (epel)
               python(abi) = 3.4
           Available: python38-3.8.2-2.amzn2.0.5.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.3-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.5-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
Error: Package: python36-chardet-3.0.4-1.el7.noarch (epel)
           Requires: /usr/bin/python3.6
Error: Package: python36-urllib3-1.25.6-2.el7.noarch (epel)
           Requires: python(abi) = 3.6
           Installed: python-2.7.18-1.amzn2.0.5.x86_64 (@amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Installed: python3-3.7.10-1.amzn2.0.1.x86_64 (@amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Installed: python38-3.8.5-1.amzn2.0.2.x86_64 (@amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python-2.7.5-58.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-2.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-4.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-5.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python3-3.7.0-0.12.b2.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.16.b3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.1-9.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.2-4.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.4.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.6-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.8-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python34-3.4.10-8.el7.x86_64 (epel)
               python(abi) = 3.4
           Available: python38-3.8.2-2.amzn2.0.5.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.3-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.5-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
Error: Package: python36-six-1.14.0-3.el7.noarch (epel)
           Requires: python(abi) = 3.6
           Installed: python-2.7.18-1.amzn2.0.5.x86_64 (@amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Installed: python3-3.7.10-1.amzn2.0.1.x86_64 (@amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Installed: python38-3.8.5-1.amzn2.0.2.x86_64 (@amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python-2.7.5-58.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.14-58.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-2.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-4.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.16-5.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.3.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.18-1.amzn2.0.4.x86_64 (amzn2-core)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python3-3.7.0-0.12.b2.amzn2.0.2.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.16.b3.amzn2.0.1.x86_64 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.0-0.20.rc1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.1-9.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.2-4.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.3-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.4-1.amzn2.0.4.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.6-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.8-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.1.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.2.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python3-3.7.9-1.amzn2.0.3.i686 (amzn2-core)
               python(abi) = 3.7
               python(abi) = 3.7
           Available: python34-3.4.10-8.el7.x86_64 (epel)
               python(abi) = 3.4
           Available: python38-3.8.2-2.amzn2.0.5.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.3-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
           Available: python38-3.8.5-1.amzn2.0.1.x86_64 (amzn2extra-python3.8)
               python(abi) = 3.8
               python(abi) = 3.8
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

  9. Installing nginx-amplify-agent package ... failed.

**Comment by chemisax** [comment]
I'm having the same problem on Amazon Linux 2 with the latest updates.

The problem seems to be that amazon includes to versions of python and that confuses the installer.
Also, if you update everything to latest, python 3.7 gets installed, some of the amplify dependencies requiere python 3.6.

I haven't found a solution yet.

**Comment by nkashiv** [comment]
@danidorado @chemisax If you are still facing this problem, please create an issue in the [NGINX Amplify Agent repo](https://github.com/nginxinc/nginx-amplify-agent/issues)
