### ISSUE TITLE
[Question] Issue with supported systems

### ISSUE THREAD

**Issue by evoke0** [nginxinc/nginx-amplify-doc#53]
Is there any chance this will be released for jammy version soon?

When trying to install nginx amplify I discovered that I couldn't due to incompatibility, since the last working version is focal fossa.
This latest version has been on for almost 3 months. I wouldn't like having to migrate back to an older version.

Thanks in advance.

**Comment by defanator** [comment]
@evoke0 yes, this work is in progress. Thanks for your interest.

**Comment by Giners** [comment]
Given the stale nature of this bug and it being unrelated to Amplify documentation the team has decided to close this bug.

If you believe there is still an issue please open a new bug in the following repo: https://github.com/nginxinc/nginx-amplify-agent
