### ISSUE TITLE
The source code for the Amplify Agent no longer exists

### ISSUE THREAD

**Issue by Makeshift** [nginxinc/nginx-amplify-doc#55]
The source code for the Amplify Agent used to be hosted under https://github.com/nginxinc/nginx-amplify-agent, but as of June 7th 2022, the repository history has been expunged and we can no longer build from source.

This also means that [this documentation](https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#source-code-for-nginx-amplify-agent) is out of date.

Where can we find the source for the amplify agent so we can install it on systems unsupported by the install script, eg alpine?

Edit: It also means that https://github.com/nginxinc/docker-nginx-amplify doesn't work, not that it was actively supported anyway.

**Comment by Makeshift** [comment]
If anyone happens to come across this while looking for an up-to-date Alpine Docker container with Nginx + Amplify Agent and doesn't feel like faffing/reverse engineering the install script - Here's my repository: https://github.com/Makeshift/docker-nginx-alpine-amplify

**Comment by larrryfisherthefisherman** [comment]
> If anyone happens to come across this while looking for an up-to-date Alpine Docker container with Nginx + Amplify Agent and doesn't feel like faffing/reverse engineering the install script - Here's my repository: https://github.com/Makeshift/docker-nginx-alpine-amplify

Thank you for this.

**Comment by Giners** [comment]
Given the stale nature of this bug and it being unrelated to Amplify documentation the team has decided to close this bug.

If you believe there is still an issue please open a new bug in the following repo: https://github.com/nginxinc/nginx-amplify-agent
