### ISSUE TITLE
PHP-FPM metrics is not receiving data.

### ISSUE THREAD

**Issue by adampatterson** [nginxinc/nginx-amplify-doc#68]
I'm not sure if I am missing something, but running the following results in a 404

```shell
SCRIPT_NAME=/status SCRIPT_FILENAME=/status QUERY_STRING= REQUEST_METHOD=GET cgi-fcgi -bind -connect /var/run/php/php8.2-fpm.sock
```

```
Primary script unknownStatus: 404 Not Found
Content-type: text/html; charset=UTF-8

File not found.
```

I ran `sudo apt install libfcgi-dev` which installed **libfcgi-dev**

Does Nginx need to know about `/status`?

My monitoring is not showing anything coming from PHP-FPM.

**Comment by nkashiv** [comment]
@adampatterson If you are still facing this problem, please create an issue in the [NGINX Amplify Agent repo](https://github.com/nginxinc/nginx-amplify-agent/issues)
