### ISSUE TITLE
Please support debian12

### ISSUE THREAD

**Issue by bithaolee** [nginxinc/nginx-amplify-doc#78]
Get:1 file:/etc/apt/mirrors/debian.list Mirrorlist [39 B]
Get:3 file:/etc/apt/mirrors/debian-security.list Mirrorlist [27 B]                                                                                
Hit:6 https://repos.insights.digitalocean.com/apt/do-agent main InRelease                                                                         
Hit:7 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease                                                                     
Hit:2 http://mirrors.digitalocean.com/debian bookworm InRelease                                                                                   
Hit:4 http://mirrors.digitalocean.com/debian bookworm-updates InRelease           
Hit:5 http://mirrors.digitalocean.com/debian bookworm-backports InRelease        
Hit:8 http://security.debian.org bookworm-security InRelease                     
Ign:9 https://packages.amplify.nginx.com/debian bookworm InRelease               
Err:10 https://packages.amplify.nginx.com/debian bookworm Release
  404  Not Found [IP: 52.24.43.197 443]
Reading package lists... Done
E: The repository 'https://packages.amplify.nginx.com/debian bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

  8. Updating repository ... failed.

 Please check the list of the supported systems here https://git.io/vKkev

root@debian-s-2vcpu:~# ^C
root@debian-s-2vcpu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

**Comment by nkashiv** [comment]
@bithaolee There is an existing issue for adding support for Debian 12 in the NGINX Amplify Agent repo: https://github.com/nginxinc/nginx-amplify-agent/issues/100.
Closing this as duplicate.
